In [17]:
import torch

torch.set_printoptions(sci_mode=False, precision=2)

In [3]:
m = torch.randn(3, 3)
m

tensor([[-0.9129,  1.3547, -0.5562],
        [-1.6466, -0.9721,  1.3118],
        [-0.6522,  0.1738,  0.4914]])

In [4]:
torch.matrix_power(m, 2)

tensor([[-1.0346, -2.6502,  2.0114],
        [ 2.2484, -1.0577,  0.2853],
        [-0.0113, -0.9670,  0.8322]])

In [5]:
torch.matrix_power(m, -1)

tensor([[-0.6455, -0.6973,  1.1308],
        [-0.0424, -0.7422,  1.9332],
        [-0.8417, -0.6631,  2.8522]])

In [6]:
torch.linalg.solve(m, -1)

TypeError: linalg_solve(): argument 'other' (position 2) must be Tensor, not int

In [8]:
A = torch.randn(3, 3)
b = torch.randn(3)
A, b

(tensor([[-1.7534,  1.0156,  0.9770],
         [-0.3774, -0.5837,  1.3343],
         [ 1.4790, -1.6633, -1.4335]]),
 tensor([ 0.3034, -0.6226, -0.3054]))

In [9]:
x = torch.linalg.solve(A, b)

In [10]:
torch.allclose(A @ x, b)

True

In [19]:
m = torch.randn(5, 5)
inv = m.inverse()

m @ inv 

tensor([[     1.00,     -0.00,     -0.00,     -0.00,     -0.00],
        [    -0.00,      1.00,     -0.00,      0.00,     -0.00],
        [     0.00,     -0.00,      1.00,      0.00,     -0.00],
        [     0.00,      0.00,      0.00,      1.00,      0.00],
        [    -0.00,      0.00,      0.00,     -0.00,      1.00]])

In [21]:
mm2 = torch.matrix_power(m, -2)
mm2

tensor([[-1.51,  1.64, -1.18, -0.59, -0.52],
        [ 0.67, -0.66,  1.63,  0.68,  0.66],
        [ 1.23, -1.89, -2.28,  1.23, -1.22],
        [-0.39,  0.31, -1.86,  0.44, -1.27],
        [ 0.16, -0.83, -2.45,  0.12, -1.28]])

In [23]:
torch.allclose(torch.matrix_power(mm2, 2), m)

False